
version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: nginx-container

  php:
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/html:/var/www/html
    depends_on:
      - mysql
    container_name: php-container

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ads_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql-container

  bind:
    image: internetsystemsconsortium/bind9:9.18
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind:/etc/bind
    container_name: bind-container

